"""Adds account status column

Revision ID: 23fd22b7814e
Revises: 56f98dd63d67
Create Date: 2026-01-05 08:33:01.469482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23fd22b7814e'
down_revision: Union[str, Sequence[str], None] = '56f98dd63d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('acc_status', sa.Enum('dormant', 'active', 'blocked', name='accountstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'acc_status')
    # ### end Alembic commands ###
