"""Decimal data type

Revision ID: 79e5db1e741f
Revises: 8d40e30466a0
Create Date: 2026-01-05 13:38:19.619608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '79e5db1e741f'
down_revision: Union[str, Sequence[str], None] = '8d40e30466a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'leverage_balance',
               existing_type=mysql.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('accounts', 'acc_balance',
               existing_type=mysql.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'acc_balance',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('accounts', 'leverage_balance',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
